[package]
name = "biodivine-aeon-py"
version = "0.2.0-alpha"
edition = "2021"

[lib]
name = "biodivine_aeon"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
biodivine-lib-param-bn = "0.3.0"
biodivine-lib-bdd = "0.4.1"
biodivine-pbn-control = { git="https://github.com/sybila/biodivine-pbn-control", branch="v0.2" }

[build-dependencies]
pyo3-build-config = "0.17.3"